# Feature Extraction

In [ ]:
!git clone -b Stable https://github.com/cvai-roig-lab/Net2Brain.git

In [ ]:
!pip install Net2Brain/.

__Net2Brain__ allows you to use one of over 600 Deep Neural Networks (DNNs) for your experiments comparing human brain activity with the activations of artificial neural networks. The DNNs in __Net2Brain__ are obtained from what we call different _netsets_, which are libraries that provide different pretrained models. 

__Net2Brain__ provides access to the following _netsets_:
- [Standard torchvision](https://pytorch.org/vision/stable/models.html) (`standard`).
This netset is a collection of the torchvision models including models for image classification, pixelwise semantic segmentation, object detection, instance segmentation, person keypoint detection, video classification, and optical flow.
- [Timm](https://github.com/rwightman/pytorch-image-models#models) (`timm`). 
A deep-learning library created by Ross Wightman that contains a collection of state-of-the-art computer vision models.
- [PyTorch Hub](https://pytorch.org/docs/stable/hub.html) (`pytorch`). 
These models are accessible through the torch.hub API and are trained for different visual tasks. They are not included in the torchvision module.
- [Unet](https://pytorch.org/hub/mateuszbuda_brain-segmentation-pytorch_unet/) (`unet`). 
Unet also is available through the torch.hub.API and is trained for abnormality segmentation in brain MRI.
- [Taskonomy](https://github.com/StanfordVL/taskonomy) (`taskonomy`). A set of networks trained for different visual tasks, like Keypoint-Detection, Depth-Estimation, Reshading, etc. The initial idea for these networks was to find relationships between different visual tasks.
- [Slowfast](https://github.com/facebookresearch/pytorchvideo) (`pyvideo`). 
These models are state-of-the-art video classification models trained on the Kinetics 400 dataset, acessible through the torch.hub API.
- [CLIP](https://github.com/openai/CLIP) (`clip`). 
CLIP (Contrastive Language-Image Pre-Training) is a vision+language multimodal neural network trained on a variety of (image, text) pairs.
- [CorNet](https://github.com/dicarlolab/CORnet) (`cornet`). 
A set of neural networks whose structure is supposed to resemble the one of the ventral visual pathway and therefore implements more recurrent connections that are commonplace in the VVS.
- [Detectron2](https://github.com/facebookresearch/Detectron) (`detectron2`). 
Facebook AI Research's software system that implements state-of-the-art object detection algorithms, including Mask R-CNN. It covers models trained for object classification and detection such as instance, panoptic and keypoint detection.
- [VISSL](https://github.com/facebookresearch/vissl) (`vissl`). 
VISSL provides reference implementation of a large number of self-supervision approaches.

You can print the available models from every netset using the function `print_all_models()`. 

In [3]:
from net2brain.feature_extraction import print_all_models

print_all_models()

Vissl models are not installed
Detectron2 is not installed.


NetSet: standard
Models: ['AlexNet', 'ResNet18', 'ResNet34', 'ResNet50', 'ResNet101', 'ResNet152', 'Squeezenet1_0', 'Squeezenet1_1', 'VGG11', 'VGG11_bn', 'VGG13', 'VGG13_bn', 'VGG16', 'VGG16_bn', 'VGG19', 'VGG19_bn', 'Densenet121', 'Densenet161', 'Densenet169', 'Densenet201', 'GoogleNet', 'ShuffleNetV2x05', 'ShuffleNetV2x10', 'mobilenet_v2', 'mobilenet_v3_large', 'mobilenet_v3_small', 'resnext50_32x4d', 'resnext101_32x8d', 'wide_resnet101_2', 'wide_resnet50_2', 'mnasnet05', 'mnasnet10', 'efficientnet_b0', 'efficientnet_b1', 'efficientnet_b2', 'efficientnet_b3', 'efficientnet_b4', 'efficientnet_b5', 'efficientnet_b6', 'efficientnet_b7', 'regnet_y_400mf', 'regnet_y_800mf', 'regnet_y_1_6gf', 'regnet_y_3_2gf', 'regnet_y_8gf', 'regnet_y_16gf', 'regnet_y_32gf', 'regnet_x_400mf', 'regnet_x_800mf', 'regnet_x_1_6gf', 'regnet_x_3_2gf', 'regnet_x_8gf', 'regnet_x_16gf', 'regnet_x_32gf']


NetSet: timm
Models: ['adv_inception_v3', 'cait_

You can also inspect the models available from a particular _netset_ using the function `print_netset_models()`:

In [4]:
from net2brain.feature_extraction import print_netset_models

print_netset_models('pyvideo')

['slow_r50', 'slowfast_r101', 'slowfast_r50', 'x3d_m', 'x3d_s', 'x3d_xs']

Or you can find a model by its name using the function `find_model_like()`:

In [5]:
from net2brain.feature_extraction import find_model_like

find_model_like('resnet50')

standard: ResNet50
standard: wide_resnet50_2
timm: cspresnet50
timm: ecaresnet50d
timm: ecaresnet50d_pruned
timm: ecaresnet50t
timm: gluon_resnet50_v1b
timm: gluon_resnet50_v1c
timm: gluon_resnet50_v1d
timm: gluon_resnet50_v1s
timm: legacy_seresnet50
timm: nf_resnet50
timm: resnet50
timm: resnet50d
timm: seresnet50
timm: ssl_resnet50
timm: swsl_resnet50
timm: tv_resnet50
timm: wide_resnet50_2
pytorch: deeplabv3_resnet50
pytorch: fcn_resnet50


## Using `FeatureExtractor` with a pretrained DNN

To extract the activations of a pretrained model from one of the netsets, you will first need to initialize the `FeatureExtractor` class, and provide the name of the model as well as the name of the _netset_. You can also determine which device to use to compute the extraction, in case you want to run it on GPUs.

In [6]:
from net2brain.feature_extraction import FeatureExtractor

fx = FeatureExtractor(model='ResNet50', netset='standard', device='cpu')

Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth


  0%|          | 0.00/97.8M [00:00<?, ?B/s]

__Net2Brain__ chooses by default from which layers of the model to extract the features from. You can inspect which layers are selected by default by calling the `layers_to_extract` attribute:

In [7]:
fx.layers_to_extract

['layer1', 'layer2', 'layer3', 'layer4']

However, you can also select which layers to extract. If you would only want the activations from specific layer, for example layer 4, you can define this is the `FeatureExtractor` arguments:

In [8]:
fx = FeatureExtractor(
    model='ResNet50', netset='standard', 
    layers_to_extract=['layer4'], 
    device='cpu'
  )

If you are not sure about the names of the layers that you could extract from a given model beyond the __Net2Brain__ default ones, you can always use the `get_all_layers()` method to get a print out of the possibilities:

In [9]:
fx.get_all_layers()

['',
 'conv1',
 'bn1',
 'relu',
 'maxpool',
 'layer1',
 'layer1.0',
 'layer1.0.conv1',
 'layer1.0.bn1',
 'layer1.0.conv2',
 'layer1.0.bn2',
 'layer1.0.conv3',
 'layer1.0.bn3',
 'layer1.0.relu',
 'layer1.0.downsample',
 'layer1.0.downsample.0',
 'layer1.0.downsample.1',
 'layer1.1',
 'layer1.1.conv1',
 'layer1.1.bn1',
 'layer1.1.conv2',
 'layer1.1.bn2',
 'layer1.1.conv3',
 'layer1.1.bn3',
 'layer1.1.relu',
 'layer1.2',
 'layer1.2.conv1',
 'layer1.2.bn1',
 'layer1.2.conv2',
 'layer1.2.bn2',
 'layer1.2.conv3',
 'layer1.2.bn3',
 'layer1.2.relu',
 'layer2',
 'layer2.0',
 'layer2.0.conv1',
 'layer2.0.bn1',
 'layer2.0.conv2',
 'layer2.0.bn2',
 'layer2.0.conv3',
 'layer2.0.bn3',
 'layer2.0.relu',
 'layer2.0.downsample',
 'layer2.0.downsample.0',
 'layer2.0.downsample.1',
 'layer2.1',
 'layer2.1.conv1',
 'layer2.1.bn1',
 'layer2.1.conv2',
 'layer2.1.bn2',
 'layer2.1.conv3',
 'layer2.1.bn3',
 'layer2.1.relu',
 'layer2.2',
 'layer2.2.conv1',
 'layer2.2.bn1',
 'layer2.2.conv2',
 'layer2.2.bn2',
 '

To initialize the extraction, you have to call the method `extract()`. Using this method, you can specify how you want the activations to be stored using the `save_format` argument. Options are (1)`pt` or (2)`npz`, in which cases the activations are stored separately for each image in a tensor or array format (respectively), or (3)`dataset`, in which case the activations are stored in the format of the `Dataset` class of the [RSA toolbox](https://rsatoolbox.readthedocs.io/en/stable/).

You can also specify in which folder to store the activations using the `save_path` argument. By default the activations will be stored in a folder named `features` at the root of the project.

In [10]:
images_path = 'Net2Brain/input_data/stimuli_data/78images'

fx = FeatureExtractor(model='ResNet50', netset='standard', device='cpu')
fts_datasets = fx.extract(
    dataset_path=images_path, save_format='dataset', save_path='features'
  )
print(fts_datasets)

100%|██████████| 78/78 [00:24<00:00,  3.23it/s]


{'layer1': rsatoolbox.data.Dataset(
measurements = 
[[0.00647232 0.00522995 0.00503027 ... 0.02912692 0.01408587 0.        ]
 [0.2340285  0.25697285 0.3446126  ... 1.254963   0.24962883 0.        ]
 [0.23590007 0.2889845  0.24829459 ... 0.8408534  1.0931451  0.        ]
 ...
 [0.32549843 0.2632195  0.25770447 ... 0.04537944 0.12915137 0.        ]
 [0.00444641 0.00473537 0.00366836 ... 0.         0.         0.3205166 ]
 [0.21026194 0.15159883 0.00472115 ... 0.2863451  0.         0.61309004]]
descriptors = 
{'dnn': 'ResNet50', 'layer': 'layer1'}
obs_descriptors = 
{'images': array(['image_01', 'image_02', 'image_03', 'image_04', 'image_05',
       'image_06', 'image_07', 'image_08', 'image_09', 'image_10',
       'image_11', 'image_12', 'image_13', 'image_14', 'image_15',
       'image_16', 'image_17', 'image_18', 'image_19', 'image_20',
       'image_21', 'image_22', 'image_23', 'image_24', 'image_25',
       'image_26', 'image_27', 'image_28', 'image_29', 'image_30',
       'image_31',

As you can see from the printout, if `dataset` is provided as the output format, the function returns a dictionary of a Dataset class with an entry for each of the layers specified. These dataset classes are stored separetely in the output folder. You can load these classes back into your code using the `load_dataset` function from the rsatoolbox dataset like so: 

In [11]:
from pathlib import Path
from rsatoolbox.data.dataset import load_dataset

filename = Path('features/ResNet50_layer1.hdf5')
layer1_dataset = load_dataset(filename, file_type='hdf5')
layer1_dataset

rsatoolbox.data.Dataset(
measurements = 
[[0.00647232 0.00522995 0.00503027 ... 0.02912692 0.01408587 0.        ]
 [0.2340285  0.25697285 0.3446126  ... 1.254963   0.24962883 0.        ]
 [0.23590007 0.2889845  0.24829459 ... 0.8408534  1.0931451  0.        ]
 ...
 [0.32549843 0.2632195  0.25770447 ... 0.04537944 0.12915137 0.        ]
 [0.00444641 0.00473537 0.00366836 ... 0.         0.         0.3205166 ]
 [0.21026194 0.15159883 0.00472115 ... 0.2863451  0.         0.61309004]]
descriptors = 
{'dnn': 'ResNet50', 'layer': 'layer1'}
obs_descriptors = 
{'images': array(['image_01', 'image_02', 'image_03', 'image_04', 'image_05',
       'image_06', 'image_07', 'image_08', 'image_09', 'image_10',
       'image_11', 'image_12', 'image_13', 'image_14', 'image_15',
       'image_16', 'image_17', 'image_18', 'image_19', 'image_20',
       'image_21', 'image_22', 'image_23', 'image_24', 'image_25',
       'image_26', 'image_27', 'image_28', 'image_29', 'image_30',
       'image_31', 'image_32'

## Using `FeatureExtractor` with your own DNN

You can also use __Net2Brain__ with your own model. For this, you will need to provide to the `FeatureExtractor` the model, the transforms of the images, and the layers to extract.

Let us see an example using a custom Alex Net:

In [12]:
from torchvision import models
from torchvision import transforms as T

# Define model and transforms
model = models.alexnet(pretrained=True)
#model = models.alexnet(weights=models.AlexNet_Weights.DEFAULT)
transforms = T.Compose([
    T.Resize((224, 224)),  # transform images if needed
    T.ToTensor(),
    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
  ])

# Define extractor
layers = ['features.0', 'features.1']
fx = FeatureExtractor(
    model=model, transforms=transforms, layers_to_extract=layers, device='cpu'
)

# Run extractor
feats = fx.extract(
    dataset_path=images_path, save_format='dataset', save_path='features2'
  )

Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /root/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth


  0%|          | 0.00/233M [00:00<?, ?B/s]

100%|██████████| 78/78 [00:05<00:00, 13.22it/s]


{'features.0': rsatoolbox.data.Dataset(
 measurements = 
 [[0.         0.         0.         ... 0.         0.7385337  3.8613157 ]
  [0.         0.         0.69632846 ... 0.         0.         0.        ]
  [0.         0.20817357 0.         ... 0.         0.9732373  0.        ]
  ...
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.9411107  0.         0.81784993 ... 0.         0.         0.44289654]
  [0.         0.1311943  0.         ... 0.         0.01381728 0.23431492]]
 descriptors = 
 {'dnn': 'Custom model', 'layer': 'features.0'}
 obs_descriptors = 
 {'images': array(['image_01', 'image_02', 'image_03', 'image_04', 'image_05',
        'image_06', 'image_07', 'image_08', 'image_09', 'image_10',
        'image_11', 'image_12', 'image_13', 'image_14', 'image_15',
        'image_16', 'image_17', 'image_18', 'image_19', 'image_20',
        'image_21', 'image_22', 'image_23', 'image_24', 'image_25',
        'image_26', 'image_27', 'image_28', 'image_29', '

## Coming Soon!

- [ ] Create researcher-friendly taxonomy of DNNs
- [ ] Optional pretrained models argument
- [ ] Optimization of extraction speed
- [ ] API documentation

### Your ideas?
- [ ]